---
baseURL: /
languageCode: de-CH
title: puzzle palooza
author:
  - Simon Flückiger
  - Daniel Schmocker
theme: PaperMod
menu:
  main:
    - name: Dokumentation
      url: dokumentation/
      weight: 5
    - name: Bilder
      url: bilder/
      weight: 10
    - name: Über uns
      url: uber-uns/
      weight: 15
params:
  defaultTheme: auto
  disableThemeToggle: false
  ShowPostNavLinks: true
  profileMode:
    enabled: true
    title: Puzzle Palooza
    subtitle: Ein modulares Making-Projekt für Schulklassen in Form eines Escape-Spiels.
    imageUrl: "/images/logo_puzzle-palooza.png"
    imageWidth: 250
    imageHeight: 250
    buttons:
      - name: Dokumentation
        url: /dokumentation
